triggers = [
    "spider",
    "spydar",
    "tarantula",
    "freya",
    "freyja",
    "spiderman",
    "spoder",
    "spoderman",
    "arachnid",
    "arachnophobia",
    "black widow",
    "daddy longleg",
    "brown recluse",
    "araneae",
    "spiders",
    "spydars",
    "tarantulas",
    "tarantulae",
    "spidermen",
    "spoders",
    "spodermen",
    "arachnids",
    "black widows",
    "daddy longlegs",
    "brown recluses",
    "bagheera kiplingi"
]